# General settings
dataset: 'CREMAD'
fusion_method: 'concat'
fps: 1
num_classes: 6
random_seed: 0

# Data paths
audio_path: './data/CREMAD/AudioWAV/'
visual_path: './data/CREMAD/Image-01-FPS/'

# Training parameters
batch_size: 64
epochs: 100
optimizer: 'sgd'
learning_rate: 0.001
lr_decay_step: 70
lr_decay_ratio: 0.1

# Checkpoint settings
ckpt_path: './ckpt'